### ISSUE TITLE
doszip 3.65 for DOS

### ISSUE THREAD

**Issue by fritzmueller** [nidud/doszip#1]
Hi Nidud,
I proposed an update of doszip to 2.65 in the FDT2312 (or later) version of FreeDOS (you sent one to me and I forwarded it)
I got the following feedback from the person who compiles the montly FreeDOS CDs:
As far as I know, we have the latest compiled DOS version 2.63.
If there is a compiled version for 2.65, please send link.
So could you please publish a complete version (source code, bin, license)  as he has less time.

Thank you very much

Fritz /  Willi

**Comment by nidud** [comment]
I added a [release for 2.65](https://github.com/nidud/doszip/releases/tag/v2.65).

The changes from 2.63:

> Changes in 2.65 - 3 Jul 2023
> - fixed empty disk error
> 
> Changes in 2.64 - 2 Jul 2023
> - fixed home directory
> 
> Changes in 2.63 - 2 Mar 2022
> - extended country-specific date format
>

**Comment by fritzmueller** [comment]
Hi Nidud,

thanks for this information.

dz 2.65 for DOS is meanwhile part of the distribution. If works fine, there is only a search bug:

If you are at C:\ of the FreeDOS HD and run a search for *.de with activated "Process subfolders"

you get FOUR results from the folders C:\games , C:\apps , but none from C:\FreeDOS\anywhere.

If your position is at C:\FREEDOS I get 275 results from the folders C:\FreeDOS\appinfo, help and nls.

This is confusing. It seems that dz does not run through all main/subfolders when searching from C:\

 

Could you please check this.

 

Thank you very very much!

 

Fritz

 

 

 
 

Sent: Friday, February 02, 2024 at 10:53 AM

**Comment by nidud** [comment]
Hi Fritz,

I fail to reproduce this error. 
I dont have real DOS at this point so I only tested emulations and it seems to work fine there.

**Comment by fritzmueller** [comment]
Enclosed the result of FDT2402 with the latest version 2.65 (DOS version). It ran on virtualbox.

 

Fritz

 
 

Sent: Tuesday, February 06, 2024 at 5:42 PM

**Comment by fritzmueller** [comment]
Hi Nidud,


referring to doszip 2.65 for DOS and the search problem:

 

I was able to fix the bug to the following:

The FreeDOS CD has a lot of ".de" (language) files in the Folder Freedos\subdirectories. So far ok. You can also try ".fr"

 

If I start a search from C:\ only the .de files in other folders are found but NOT the .de files at C:\freedos.

If I start a search from C:\freedos the .de files in this folder are found. (everything with checked "process subfolders")

And now the strange thing:

I created a folder C:\test, copied all files from C:\freedos to C:\test and ran a search from C:\

The result showed me the .de files from all folders including C:\test but NOT from C:\freedos although it should be identical.

I have no idea why C:\freedos results are forgotten. An attribute problem?

 

One more thing that I noticed, is that the search ends at 999 search hits. But this cannot be the reason,

as C:\ AND the C:\freedos folder has less than 999 .de search hits.

 

I hope you can reproduce this behaviour now.

 

Fritz / W. Spiegl

**Comment by nidud** [comment]
> An attribute problem?

That was my first assumption and I've tried a few combinations to no avail, but it have to be something specific to this directory which prevent read access.

> One more thing that I noticed, is that the search ends at 999 search hits.

This normally happens if multiple strings are found in the same file but this could also be a read related problem (duplicated files). I will assume this relates to the `findfirst/findnext` functions, which may not be fully supported (or behave differently) in VirtualBox.

**Comment by fritzmueller** [comment]
Hi Nidud,
I installed Freedos 2403 version on a real machine twice today. i crated a file test.bat and copied it into all main folders to see if all are found. the file in folder freedos was not found both times, one time it did not find the file in folder util and one time the folder net.
I will try to test it on fat 16.
the command dir /s test.bat found all files.

Just for info.

Willi

**Comment by nidud** [comment]
The scan code skipped the two first entries (assumed to be "." and "..") so this failed in the root directory as the first entry (FreeDos in this case) was never searched.

I added a new release: doszip-2.66Dos16

**Comment by fritzmueller** [comment]
Hi Nidud,
I have a problem with doszip 2.68 (DOS version).
Whenever I press F4 to edit a text file (even test.txt, 13 Byte) I get an error message:

Error. Not enough space. OK

Tested with FreeDOS 2512 on virtualbox with 32 MB RAM and 1,96 GB virtual HD. It worked fine with version 2.66

**Comment by nidud** [comment]
Maybe there's to many open files? Try F9 or Alt-0
What says File->Memory Information (Alt-M)?

**Comment by fritzmueller** [comment]
Good question, when I boot from vbox HD directly, enter dz and then F9 I get a red message box from C:\  : "Directory not found: C:\freedos\bin\edi .

Create this directory. OK / Cancel.  Ehm, sorry, this was version 2.66. But also with version 2.68

 

ah, ALT-F9 reports PANIC: before 4A MCB chain corrupted. System halted. DOS mem corrupt. First_mcb 0291.

Nothing with ALT-O or ALT-0.

ALT-M reports 654.336 Bytes conventional memory, 34576 bytes used, ? byte EMS memory and ? byte used. But now edit (F4) seems to work again.

 

 

Fritz

 

 
 

Sent: Saturday, December 13, 2025 at 5:32 PM

**Comment by nidud** [comment]
There was a memory issue.

Added a new DOS version:
https://sourceforge.net/projects/doszip/files/DOS/
