### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [nidud/doszip#1]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D1%84%D0%B0%D0%B9%D0%BB%D1%8B-%D0%B8-%D0%BF%D0%B0%D0%BF%D0%BA%D0%B8/doszip-commander.html).

There is a problem with displaying a file with names in Russian, apparently only names in ANSI are supported, and not in UNICODE.
![Снимок](https://user-images.githubusercontent.com/14289360/97133597-2429c480-177d-11eb-82fa-43f0fd1662b1.png)

The project is interesting, so please don't abandon it!

**Comment by nidud** [comment]
Should work if the console has the correct code page and fonts.
`mode con codepage`

What happens if you issue a DIR command, does the files display correctly?

**Comment by mrkaban** [comment]
entered the specified command but nothing changed. How do I change the encoding? and how to open a tab?

**Comment by nidud** [comment]
Doszip is a text based console application so it will use the local language setting and font to display files.

The first command display the current language setting. On my end I will get the following output (use Ctrl-B, F11, or Alt-Up to view the output):
```
Status for enhet CON:
-----------------------
    Tegntabell:     850
```
So the message is displayed in my native language (Norwegian) and the code page used is 850 (think the Russian code page is 866).

The second command (DIR) will list the files in the current directory. This is done by the OS so it will show if Windows display the files correctly in the console.

It's also possible to set the desired language with the MODE command:
`mode con cp select=866`

**Comment by mrkaban** [comment]
![Снимок](https://user-images.githubusercontent.com/14289360/97298992-d39e8e00-1886-11eb-92d4-8051525b7513.png)

with 866 encoding, file names are displayed incorrectly, but if you put 1251, then it is normal, but the dividing lines of the panels are displayed incorrectly.

**Comment by nidud** [comment]
What was the default setting from the first test (`mode con codepage`)?

When I flip the code page I get this:
850:
![850](http://masm32.com/board/index.php?action=dlattach;topic=6221.0;attach=6484;image)
866:
![866](http://masm32.com/board/index.php?action=dlattach;topic=6221.0;attach=6485;image)

**Comment by mrkaban** [comment]
The default code page is 866, if you put 850, the same problem.

**Comment by nidud** [comment]
Maybe some changes to the console output to support a global code page could be added so I will look into that.

**Comment by nidud** [comment]
It could however be a font problem on your end, that the console fonts for 866 is missing.

**Comment by mrkaban** [comment]
There are no such problems in Far Manager.
![Uploading Снимок.png…]()

**Comment by mrkaban** [comment]
There are no such problems in Far Manager.
![Снимок](https://user-images.githubusercontent.com/14289360/97307668-92ac7680-1892-11eb-8650-3ae09e7ef9e4.png)

**Comment by nidud** [comment]
Yes, that is a Unicode application.

DZ use some Unicode functions for system operations but the application is ASCII.

**Comment by nidud** [comment]
You should however be able to use Russian ASCII characters on your computer (assuming you have a Russian keyboard) so what happens if you write some Russian text on the command line or in the editor?

If what you write differ from what you see on the screen there's something wrong with the font installed for code page 866.

**Comment by mrkaban** [comment]
If you just write without commands, then it is displayed without problems
![Снимок](https://user-images.githubusercontent.com/14289360/97322124-102bb300-18a2-11eb-9fdf-dd75e37d11bc.png)

**Comment by nidud** [comment]
Okay, so it basically works then.

As an exercise try to create a directory in the ./dz folder with DZ (F7) with the same name as one who failed. Maybe the one on the Desktop after Open-Sitemap (HOTbl (in Russian)) and see how that goes.

Does it display correctly in DZ?
If so, does it also display correctly in Far and Explorer?

**Comment by mrkaban** [comment]
similarly with notes
![Снимок](https://user-images.githubusercontent.com/14289360/97328542-b4b0f380-18a8-11eb-9017-8e22c5f91cb9.png)

**Comment by nidud** [comment]
So Windows (and Far) regards the Russian language to be foreign on your machine, which means that you don't have a Russian version of Windows (I guess an English version with a language-pack)?

In that case all languages (except English) will be regarded as foreign on your system, so you need Unicode to access (or at least display) files correctly.

**Comment by mrkaban** [comment]
Perhaps, but for the average layman (user), everything is a little easier. It works here, it doesn't work there.

**Comment by nidud** [comment]
True, and it's also possible to fix the layout by using a global code page. But creating files/directories (at least in a local language), edit/view and all things ASCII becomes a problem.

DZ is primarily used as a shell for setting up programming environments and this includes source code, configurations, documentations, and command line tools which are all ASCII based.
