### ISSUE TITLE
Is there a Dos and Win build somewhere, and how to donate?

### ISSUE THREAD

**Issue by GHExplorer** [nidud/doszip#10]
Hi,

Sourceforge has the binaries from 2019.  But I haven't been able to locate the most recent versions.

Also, is there a way to thank the developer with a Paypal donation?  This is really good, based on the binary from 2019.  It looks and feels solid & natural.

**Comment by nidud** [comment]
Hi,

> Sourceforge has the binaries from 2019. But I haven't been able to locate the most recent versions.

You can download the latest version here:
https://github.com/nidud/doszip/releases

> Also, is there a way to thank the developer with a Paypal donation?

No.

**Comment by GHExplorer** [comment]
Ok, thanks nidud.
