### ISSUE TITLE
Alternate keys for selecting files

### ISSUE THREAD

**Issue by ltning** [nidud/doszip#11]
Incredible tool, thank you!
I have some (old and new) machines without numeric keypads, so e.g. numpad `*` doesn't exist. Other NC-workalikes have the same problem: there's no alternative to numpad `*` to toggle selection of all files.
In e.g. Midnight Commander I'd use `+` to pop up a dialog allowing me to input a file mask for toggling/selecting (defaulting to `*.*`, but sadly not including directories). 
Can an alternate way of toggling all be added to DosZip? I'm only using the DOS version; not sure if this is applicable to the win32 version. It would be if you had an OS/2 version though ;-)

**Comment by nidud** [comment]
Hi Eirik,

> I have some (old and new) machines without numeric keypads

I guess you have to use the Edit menu (Alt+E) in that case. There's also a Panel Option (Ctrl+P) to toggle Select Directories.

**Comment by ltning** [comment]
No hope of assigning an alternate key? Going through the menus kinda interrupts an otherwise smooth workflow :)
(Sorry for re-opening the ticket; feel free to close it again.)

**Comment by nidud** [comment]
Think the key-options are more or less maxed out at this point, at least for the regular key bindings. As the keyboard you use do not have a keypad the options are even less, but if you have some suggestions I will look into it.

There are some options to select all files (Ctrl-C) if you dont need a mask, and a read mask can be set for the panel if it's a specific type you using.
