### ISSUE TITLE
Problems with adding diskettes and HDs without label / ".." (doubledot)

### ISSUE THREAD

**Issue by fritzmueller** [nidud/doszip#12]
See https://sourceforge.net/p/freedos/bugs/379/ . There seem to be two bugs with the reported and the latest DOS version of dz.
a) The DOS version shows a ".." (doubledot) symbol at the root of the HD partition or diskette. I have never seen a doubledot on the root before, only in subdirectories. When you doubleclick on ".." you get an error message.
b) When a diskette has no label it is not accepted (I assume because only ".." is there - and as it has problems with it. Create a file and it works as expected, delete the file and the error message appears again.
c) The same like b) happens if you add a HD to your system, run fdisk WITHOUT giving a label while running format. Then dz does not accept the formatted HD. Run label with a name and dz accepts the new HD. Remove label and is no longer accepted (I wrote no files on it, when I added a file via command line, the error message disappeared and appeared again as soon as I deleted the file).

Could you please check this.

![Error-when- doubleclicking-on dot-dot](https://github.com/nidud/doszip/assets/43041549/66cc06dc-5021-4ca3-984c-48e5577c686e)

![Error-without-label-and-other-file](https://github.com/nidud/doszip/assets/43041549/9d4754c9-f166-434a-9d1e-8dcefd439c5a)

**Comment by nidud** [comment]
There's a` home` above the root directory (Ctrl-Home) listing available disks. I added a fix for this in v2.64.

I didn't test the label issue.

**Comment by fritzmueller** [comment]
Hello Nidud, 
the doubledot seems to be fixed now. When clicking on it you can directly choose one of the existing drives. A good idea!

As it turns out to me the "label" problem is as follows:
Label seems to be written on two different positions when running fdisk (or format on diskette). One time anywhere in the bootsector (at least HD), the second time it is written as an empty "file" on the HD. As it looks like, dz does not accept a diskette or HD that has NO file on the surface. As label is one of the first things that are written on the diskette / HD there is a file and dz works. If there is no label set, there is no file on the surface and dz gives an error message. If you create a file on the diskette / HD via commandline (e.g. by copy or echo blabla > a:\file.txt) there is one file and dz works.
This theme has already been discussed in one of the FreeDOS forums including screenshots, see:

https://sourceforge.net/p/freedos/bugs/365/

It would be great if you could check and fix this.

Thx.
Fritz

**Comment by nidud** [comment]
The code is somewhat sensitive as it needs to test if the drive exist for the missing floppy/CD/device loop.

The way this is done is an attempt to read `*.*` from the disk which usually succeeds if a file or a volume-id is present. There are many other ways of testing if a disk is ready but it becomes rather complicated as it depends on too many things (OS type/version) so the most portable way seems to be the read options. It is however not very reliable with regards to error code, so it will return the same for an empty disk as for a missing CD. 

One thing that may (or may not) work is an attempt to read `NUL` if the above fails. I added this to the zip below so maybe you could test if that works.
[doszip-2.65Dos16.zip](https://github.com/nidud/doszip/files/11937540/doszip-2.65Dos16.zip)

**Comment by fritzmueller** [comment]
Hi Nidud,
a great job, now it works as expected.

Fritz
