### ISSUE TITLE
v2.55 (DOS): Move dialog color issue

### ISSUE THREAD

**Issue by bttrx** [nidud/doszip#3]
When I enable confirmation for Move operations and then press F6 for Move, I can see the proposed filename black on cyan.
But when I start typing or navigation the filename, the filename switches to black on black. That makes it a little hard to adjust the name. ;-)

**Comment by nidud** [comment]
This seems to depend on color selection but I did the same as for the Copy dialog as that appear to work.

**Comment by bttrx** [comment]
> This seems to depend on color selection but I did the same as for the Copy dialog as that appear to work.

Yes, probably. I'm using the default color set, because I didn't understand how your color sets work. The Copy dialog works fine for me, yes.

**Comment by bttrx** [comment]
Tested in version 2.56 and the Move dialog seems to be fixed. Thanks!
