### ISSUE TITLE
v2.56 (DOS): Regression loading/saving settings

### ISSUE THREAD

**Issue by bttrx** [nidud/doszip#6]
With the latest version I now have the problem, that it doesn't remember its configuration. With v2.55 it worked fine.

According to the timestamp, the dz.cfg file is updated on exit, when Autosave is on. Also when save the configuration immediately by pressing Shift+F9.
After I restart DZ everything, e.g., panel settings, use Int 2Fh, confirmation for Move dialog, has been reverted to default.
This also effects running a command from DZ. After a simple "dir" command, all custom configuration is lost.

By the way: Would you mind updating history.txt, when releasing a new version? :-) Missing history for versions 2.53 to 2.55 is at https://sourceforge.net/projects/doszip/files/DOS/

**Comment by nidud** [comment]
Been playing with DOS of late so there was some other libraries tangle up in the latest build. This should be fixed now and I'v added the history file.

**Comment by bttrx** [comment]
Thanks Hjort! I'll try tomorrow.

**Comment by bttrx** [comment]
Works perfectly well. :-)

Just a few minor notes:
- Help -> About says "(C) 97-2016". Should be "97-2022" as in doszip.txt.
- "Help -> About -> License" fails to open license.txt from %dz% or %doszip% dir, because you distribute ..\LICENSE instead.
- Distribute history.txt also (or only?) in the doszip-2.XXDos16.zip binary package. Users want to know, what changed between versions. At least when something breaks. ;-)
A version 2.58 would be nice now, so we don't forget about.

**Comment by bttrx** [comment]
Thanks for fixing.
Only thing _not_ fixed is: Stub DZ.EXE also prints "1997-2016
