### ISSUE TITLE
(DOS): Add COUNTRY support

### ISSUE THREAD

**Issue by bttrx** [nidud/doszip#7]
Hi Hjort,
this is a feature request only, because implementation would be a major change. So take your time.
In doszip.txt you say "The date format is (Norwegian) dd.mm.yyyy".
That's perfectly nice for me, because that's the format we use in Germany too.
But many people in the world, e.g., in the USA or UK, use "mm/dd/yyyy" and might get confused how dates are displayed in DZ.
Different format are also used for time, numbers.
Please see http://www.ctyme.com/intr/rb-2773.htm for details.
Cheers,
Robert
P.S.: Thanks for still maintaining DZ! :-)

**Comment by nidud** [comment]
I added country-specific date format but not sure if it actually works. I use the msdos.exe extender for testing and flipping code pages didn't have any effect, so it may or may not work.

**Comment by bttrx** [comment]
It works. Congrats! :-)

Although countries, languages, and codepages connect to each other, just flipping codepages doesn't change country data. I don't know msdos.exe extender, but in plain DOS you need to add or adjust a COUNTRY= line in CONFIG.SYS. Maybe DOSBox works better for you, but I didn't try. I run DOS in a VirtualBox VM.

I looked at your [commit](https://github.com/nidud/doszip/commit/050132889c82b49525e522456a70434fdf7cc7d8) and noticed two issues:
1. You don't support the Japanese date format YMD. It is not only used in Japan, but also in Korea, China, Hungary, Sweden. To just name a few.
2. You use a hardcoded "/" or "." as a date separator. This is not necessary, because DOS can give you the date separator (and the time separator) from the actual system:
   - offset 0Bh  2 BYTEs   ASCIZ date separator
   - offset 0Dh  2 BYTEs   ASCIZ time separator

Please see https://github.com/FDOS/country/blob/master/country.asm#L2989 for the many possible combinations of formats and separators.

(For including by you, I placed a TAB-corrected LICENSE file at http://www.bttr-software.de/tmp/LICENSE.zip.)

**Comment by nidud** [comment]
The [MS-DOS Emulator for Win64 (msdos.exe)](http://takeda-toshiya.my.coocan.jp/) is handy as you can run DOS applications directly from the command line.

I extended the date to YMD but it needs testing. This also include string to date functions used in File Attributes/Filter dialogs.

**Comment by bttrx** [comment]
Although your code on GitHub says something different, the date and time separators are not honored by v2.59.

I also noted a new problem: Now, that we support 12-hours-time display, users can't distinguish between AM or PM. Norton, Volkov, and other commanders solved this by making the Size column smaller. This gives room to append "a" or "p" in the time column.

This is, how Volkov Commander looks:
![VirtualBox_SvarDOS_19_02_2022_13_14_56](https://user-images.githubusercontent.com/15858666/154800328-763490cb-b0a6-4036-93bb-7dbb63ee46a5.png)

**Comment by nidud** [comment]
The Int 21/38 call fails here so I will guess that's the same on your end.

**Comment by bttrx** [comment]
I don't think it fails, because the date format (MDY, DMY, YMD) is applied correctly.

**Comment by nidud** [comment]
The time/date chars need DOS 2.11+ so this defaults to ':' / '.' or '/' for  MDY and YMD, so if it doesn't fail this should work.

**Comment by bttrx** [comment]
I understand. But then there must be a bug in your code, because Volkov Commander, my own "country information", and other tools, also use Int21.38 and work as expected.

**Comment by nidud** [comment]
Note that the time format is still 24 so the only change is the time separator used in the file panel. The bug must then be the date separator for MDY and YMD.

**Comment by nidud** [comment]
It's two bytes so I just grabbed the first char there.

`
0Bh  2 BYTEs   ASCIZ date separator`

**Comment by bttrx** [comment]
Which is correct.

I think, I found your problem: In https://github.com/nidud/doszip/blob/4e2bf5134aa7c6909d43c8b715c71aa50a62fee5/dos/lib/src/time/timeinit.asm#L51 you jump to the end of function, but you would better to https://github.com/nidud/doszip/blob/4e2bf5134aa7c6909d43c8b715c71aa50a62fee5/dos/lib/src/time/timeinit.asm#L53

At least, this worked for me, when I changed DZ.DOS using a hex editor after uncompressing.

**Comment by nidud** [comment]
Added this and updated Date and Time.

**Comment by bttrx** [comment]
Tested and noted, that you also did something else, because it doesn't work as expected. DZ always showed the date in format MM/DD/YY. (= US)

This is the current code from your GitHub repo:
```
timeinit PROC PRIVATE
LOCAL	country_info[64]:byte
	push	ds
	push	ss
	pop	ds
	mov	country_info,DFORMAT_EUROPE
	lea	dx,country_info
	mov	ax,3800h
	stc
	int	21h
	pop	ds
	jc	toend
	mov	al,country_info
	mov	dos_dateformat,al
	cmp	al,DFORMAT_EUROPE
	je	europe
	mov	al,'/'
europe:
	cmp	_osmajor,2
	ja	dos_2_11
	cmp	_osminor,11
	jb	dos_2_10
dos_2_11:
	mov	al,country_info[0x0D]
	mov	time_separator,al
	mov	cp_timefrm[3],al ; "%2u:%02u"
	mov	al,country_info[0x0B]
	mov	date_separator,al
dos_2_10:
	mov	cp_datefrm[3],al ; "%2u.%02u.%02u"
	mov	cp_datefrm[8],al
toend:
	ret
timeinit ENDP
```
And this is what a disassembler shows to me:
![VirtualBox_SvarDOS_19_02_2022_20_54_03](https://user-images.githubusercontent.com/15858666/154816917-b94dde21-84da-40d3-b1d4-c2214b411930.png)

That code sequence from 0xEB53 to 0xEB5C is NOT in your source code snippet above and it doesn't make sense to me at all:
EB50 get date format from buffer filled by DOS Int21.38
EB53 AL = 0, used at EB59
EB55 set (!) date separator in buffer to '/'
EB59 dos_dateformat = 0 (US = MDY)

I had to nuke this sequence with NOPs (0x90) to make v2.60 work.

Please always post the source code you actually used to build a binary to GitHub. ;-)

**Comment by bttrx** [comment]
If you are a funny guy like I am, you can make DZ date & time look like this:
![VirtualBox_SvarDOS_19_02_2022_21_21_47](https://user-images.githubusercontent.com/15858666/154817785-02687634-0080-4b87-9d99-941c92f9c118.png)

**Comment by nidud** [comment]
> That code sequence from 0xEB53 to 0xEB5C is NOT in your source code snippet above and it doesn't make sense to me at all:

As the interrupt fails on my end I need to preset the values for JAPAN/USA in order verify and test the output.

The hack also failed as the value ('.') needs to be preset.

**Comment by bttrx** [comment]
v2.61 seems to work now for me, at least for the date and time column and the clock display in the upper right. Hooray! :-)
(And I was able to build DZ from sources for testing.)

When I press Ctrl+A display is fine, but when I change values, they will be set wrong. Will add some screenshots later.

**Comment by nidud** [comment]
https://github.com/nidud/doszip/blob/master/dos/lib/src/time/twtostr.asm#L11

Should be:
`	mov	cl,time_separator
`

**Comment by bttrx** [comment]
> In 1 and 2 the header should probably be set to 'data' and 'time' instead.
> 
I'm fine with that.
> In point 3 I assume '!' and '#' are correct?
> 
Yes. (And yes, this is only an example "fantasy" country setting for demonstration.

**Comment by nidud** [comment]
I updated the dialog and the code above in v2.62.

**Comment by bttrx** [comment]
Works! :-)

But this old LICENSE file with the two missing TAB chars slipped in again.

And 'Hexadesimal' in the search dialog should be 'Hexadecimal' (with 'c', not 's').

**Comment by nidud** [comment]
Fixed.

The time format is also updated in the Win32 version 3.61. I haven't tested this but I guess you use the same format as we do.

**Comment by bttrx** [comment]
I tested the 2.63 release for DOS only and it seems perfect now. :-)

Thanks for all your efforts on this topic. I will close this ticket now.
