### ISSUE TITLE
Bug report of a FreeDOS tester

### ISSUE THREAD

**Issue by fritzmueller** [nidud/doszip#8]
Hi,
this is a bug report of a FreeDOS tester who doesn't like Github and Gitlab. He asked me to forward it to you:

There was a formating error i mean, if i search for a pattern like:

" *basic*.* " (asterisk before and after basic!)

Then it shows every file. But it shouldn't.

I tested it and it seems to be correct. Doszip - File - Search - Find Files: " *xyz*.* " (search for something where xyz is within filename, asterisk xyz asterisk.asterisk).
Thanks for reading

Fritz

**Comment by nidud** [comment]
> " basic.* " (asterisk before and after basic!)

Not sure I understand this correctly but basic.* will only show files named basic, and \*basic.\* will show all files that end with the name basic:

![](https://raw.githubusercontent.com/nidud/doszip/master/img/FileSearchBasic.png)

**Comment by bttrx** [comment]
Hi Fritz,
nice to see you _here_ too! :-)
The intention of your anonymous FreeDOS tester is clear, but that's not, how DOS file searching works.
If you run "dir *dep*.* /s" you will get all files too, because the first "*" already means "any characters on the left of ."
Cheers,
Robert

**Comment by nidud** [comment]
It does actually work in emulated environments so from \*dep\*.\* I get:

`
/../gement.deployment.inc
`

Note that *asterisk* is a format char here: \\\*dep\\\*.\\\*

**Comment by bttrx** [comment]
> [...] because the first "*" already means "any characters on the left of ."

My explanation was wrong. Correct is: "*" means "any character 0 times, 1 time, or many times". That just matches anything, when used as in "*term*".
