### ISSUE TITLE
DOSZIP COMMANDER 3.61 (win32) doesn't run under WinXP.

### ISSUE THREAD

**Issue by xrayer** [nidud/doszip#9]
I tried to rebuild from sources using current ASMC and OWC but didn't help.
I had to manually fix some missing imports.

dz.exe didn't run under WinXP due to missing imports from kernel32.dll, patched:
GetDateFormatEx -> GetDateFormatA
GetTimeFormatEx -> GetTimeFormatA

I also have similar problem with make.exe from ASMC package.
make.exe didn't run under WinXP due to missing import of func
_get_pgmptr from msvcrt.dll
this functions is present in msvcr100.dll so I patched library name in make.exe

Unfortunatelly replacing
GetDateFormatEx -> GetDateFormatA
GetTimeFormatEx -> GetTimeFormatA
led to invalid display of date & time in panels. I think it could be fixed by some ifdef with different codepath for WXP and newer Win, would be a pitty to break compatability just due to 2 minor functions...

**Comment by nidud** [comment]
> I also have similar problem with make.exe from ASMC package.
make.exe didn't run under WinXP due to missing import of func
_get_pgmptr from msvcrt.dll
this functions is present in msvcr100.dll so I patched library name in make.exe

I uploaded a new build of make.exe using the static library so this should work now.

**Comment by xrayer** [comment]
Hi, make.exe now works under XP.
I can test updates on XP for you.
When I replaced that 2 functions (patched compiled binary) the displayed time seems to be some kind shifted - e.g. file time 6:07 is displayed as 0:70 and date instead of 15.03.22 is displayed as 1..02
http://rayer.g6.cz/1tmp/dz-w32.png

**Comment by nidud** [comment]
GetDateFormat seems to work in Win 10 so we need test how the output is in XP. I attached a simple test case here:
```
include io.inc
include time.inc
include stdio.inc
include winnls.inc
include winbase.inc
include tchar.inc

    .code

_tmain proc

   .new FindFileData:WIN32_FIND_DATA

    FindClose(FindFirstFile("GetDateFormat.asm", &FindFileData))

   .new LocalTime:FILETIME
   .new SystemTime:SYSTEMTIME

    FileTimeToLocalFileTime(&FindFileData.ftLastWriteTime, &LocalTime)
    FileTimeToSystemTime(&LocalTime, &SystemTime)

   .new dateString[MAX_PATH]:char_t
   .new timeString[MAX_PATH]:char_t
   .new id:LCID = GetUserDefaultLCID()

    GetDateFormat(id, DATE_SHORTDATE, &SystemTime, NULL, &dateString, lengthof(dateString))
    GetTimeFormat(id, TIME_FORCE24HOURFORMAT, &SystemTime, NULL, &timeString, lengthof(timeString))
    _tprintf("time: %s\ndate: %s\n", &timeString, &dateString)

    GetTimeFormat(id, TIME_FORCE24HOURFORMAT or TIME_NOSECONDS, &SystemTime, NULL, &timeString, lengthof(timeString))
    _tprintf("time: %s\n", &timeString)
    .return( 0 )

_tmain endp

    end _tstart

```
[GetDateFormat.zip](https://github.com/nidud/doszip/files/8262487/GetDateFormat.zip)

The output on my end:
```
time: 13:59:33
date: 16.03.2022
time: 13:59
```
The assumption here is that it's zero-padded so the time string is cropped for short time. The same for the date, so if date[2] is a digit it starts with year (yyyy), else the last four chars is the year.

**Comment by xrayer** [comment]
The test output seems to be correct:

L:\ASMC\bin>asmc -pe GetDateFormat.asm
Asmc Macro Assembler Version 2.33.45
Copyright (C) The Asmc Contributors. All Rights Reserved.

 Assembling: GetDateFormat.asm

L:\ASMC\bin>GetDateFormat.exe
time: 13:59:32
date: 16.3.2022
time: 13:59

L:\ASMC\bin>asmc -pe -ws GetDateFormat.asm
Asmc Macro Assembler Version 2.33.45
Copyright (C) The Asmc Contributors. All Rights Reserved.

 Assembling: GetDateFormat.asm

L:\ASMC\bin>GetDateFormat.exe
time: 13:59:32
date: 16.3.2022
time: 13:59

**Comment by xrayer** [comment]
I recompiled from git-master and it seems fixed now. Runs under WinXP and time/date format dysplays OK. Thanks. So I close this issue.
